name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: 'us-east-2'
   steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform                                                                      
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        id: init
        run: cd stage && terraform init  
        
      - name: Show Destroy plan
        run: cd stage && terraform plan -destroy
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: cd stage && terraform destroy -auto-approve